# Generated by Django 4.2.7 on 2025-10-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('water_flosser', 'Máy tăm nước'), ('electric_brush', 'Bàn chải điện'), ('mouthwash', 'Nước súc miệng'), ('other', 'Sản phẩm khác')], max_length=20, verbose_name='Danh mục'),
        ),
    ]
