# Generated by Django 4.2.7 on 2025-09-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
