# Generated by Django 4.2.7 on 2025-10-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('file', models.FileField(upload_to='media_assets/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video'), ('document', 'Tài liệu')], default='image', max_length=50, verbose_name='Loại file')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tài nguyên Media',
                'verbose_name_plural': 'Tài nguyên Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Giá trị')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Cài đặt trang web',
                'verbose_name_plural': 'Cài đặt trang web',
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('position', models.CharField(choices=[('hero', 'Hero Section'), ('category_banner', 'Category Banner'), ('sidebar_banner', 'Sidebar Banner'), ('footer_banner', 'Footer Banner'), ('widget_1', 'Widget 1'), ('widget_2', 'Widget 2'), ('widget_3', 'Widget 3'), ('featured', 'Featured')], max_length=50, verbose_name='Vị trí')),
                ('image', models.ImageField(upload_to='page_images/', verbose_name='Hình ảnh')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='URL liên kết')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hình ảnh trang',
                'verbose_name_plural': 'Hình ảnh trang',
                'ordering': ['-created_at'],
                'unique_together': {('position',)},
            },
        ),
    ]
