# Generated by Django 4.2.7 on 2025-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['category', 'key'], 'verbose_name': 'Cài đặt trang web', 'verbose_name_plural': 'Cài đặt trang web'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='category',
            field=models.CharField(choices=[('company', 'Thông tin công ty'), ('contact', 'Thông tin liên hệ'), ('social', 'Mạng xã hội'), ('seo', 'SEO & Tracking'), ('other', 'Khác')], default='other', max_length=50, verbose_name='Danh mục'),
        ),
    ]
