# Generated by Django 4.2.7 on 2025-10-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_sitesetting_options_sitesetting_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageimage',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Hình ảnh trang', 'verbose_name_plural': 'Hình ảnh trang'},
        ),
        migrations.AlterUniqueTogether(
            name='pageimage',
            unique_together=set(),
        ),
    ]
