# Generated by Django 4.2.7 on 2025-10-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_pageimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='position',
            field=models.CharField(choices=[('hero', 'Hero Section (Trang chủ)'), ('tamnuoc_banner', 'Banner Máy tăm nước'), ('banchaidien_banner', 'Banner Bàn chải điện'), ('nuocsucmieng_banner', 'Banner Nước súc miệng'), ('sanphamkhac_banner', 'Banner Sản phẩm khác'), ('widget_1', 'Widget 1'), ('widget_2', 'Widget 2'), ('widget_3', 'Widget 3'), ('featured', 'Hình ảnh nổi bật')], max_length=50, verbose_name='Vị trí'),
        ),
    ]
