# Generated by Django 4.2.7 on 2025-10-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_pageimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='position',
            field=models.CharField(choices=[('hero', 'Hero Section (Trang chủ)'), ('tamnuoc_banner', 'Banner Máy tăm nước'), ('banchaidien_banner', 'Banner Bàn chải điện'), ('nuocsucmieng_banner', 'Banner Nước súc miệng'), ('sanphamkhac_banner', 'Banner Sản phẩm khác'), ('hero_section', 'Hero Section (Trang giới thiệu)'), ('story_section', 'Story Section (Trang giới thiệu)'), ('ourteam_section', 'Our Team (Trang giới thiệu)')], max_length=50, verbose_name='Vị trí'),
        ),
    ]
