# Generated by Django 4.2.7 on 2025-10-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_pageimage_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaAsset',
        ),
    ]
